/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  pullRequestUtils: [{ type: "autogenerated", dirName: "extensions/pull-request-utils" }],
  autoState: [{ type: "autogenerated", dirName: "extensions/auto-state" }],
  envTransform: [{ type: "autogenerated", dirName: "extensions/env-transform" }],
  gitGuard: [{ type: "autogenerated", dirName: "extensions/gitguard" }],
  azext: [{ type: "autogenerated", dirName: "tools/azext" }],
  guide: [{ type: "autogenerated", dirName: "guide" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
